sudo: false
language: c

## whitelist
branches:
  only:
    - build-ci

compiler:
  - gcc

env:
  global:
  - LANG=C

addons:
   apt:
     packages:
     - g++
     - gccxml
     - reprepro
     - devscripts
     - docbook-to-man
     - libgc-dev
     - libperl-dev
     - libgc1c2
     - coreutils
     - netcat-openbsd
     - curl

install:
- ./install.sh -plain -bootstrap

