sudo: false
language: c

## notifications
notifications:
   email: off
      # on_success: change  ## [always,never,change]
      # on_failure: always  ## [always,never,change]
      
   ## IRC
   irc: "chat.freenode.net#liberty-eiffel"
      on_success: never  ## [always,never,change]
      on_failure: never  ## [always,never,change]


## whitelist
branches:
  only:
    - build-ci

## whitelist - end

compiler:
  - gcc

env:
  global:
  - LANG=C

addons:
   apt:
     packages:
     - g++
     - gccxml
     - reprepro
     - devscripts
     - docbook-to-man
     - libgc-dev
     - libperl-dev
     - libgc1c2
     - coreutils
     - netcat-openbsd
     - curl

# before_install:

# install:

# before_script:

script:
     - ./install.sh -plain -bootstrap

# after_failure

# after_success

## optional
# before_deploy:

## optional
# deploy:

## optional
# after_deploy:

after_script:
     - echo "******************************************************"
     - echo "**           Liberty settings                       **"
     - echo "******************************************************"
     - cat target/liberty-eiffel/liberty.se
     - echo ""
     - echo ""
     - echo "******************************************************"
     - echo "**            Installation Log file                 **"
     - echo "******************************************************"
     - cat target/log/install*log

