sudo: false
language: c

## notifications
notifications:
   email: off

## whitelist
branches:
  only:
    - master

## whitelist - end

compiler:
  - gcc

env:
  global:
  - LANG=C

addons:
   apt:
     packages:
     - g++
     - gccxml
     - reprepro
     - devscripts
     - libgc-dev
     - libperl-dev
     - libgc1c2
     - coreutils
     - netcat-openbsd
     - curl

# before_install:

# install:

# before_script:

script:
     - ./install.sh -plain -bootstrap

after_failure:
     - echo "******************************************************"
     - echo "**           Liberty settings                       **"
     - echo "******************************************************"
     - cat target/liberty-eiffel/liberty.se
     - echo ""
     - echo ""
     - echo "******************************************************"
     - echo "**            Installation Log file                 **"
     - echo "******************************************************"
     - cat target/log/install*log


# after_success:

## optional
# before_deploy:

## optional
# deploy:

## optional
# after_deploy:

# after_script:




##### END OF FILE #####